{% set version = "0.5.0" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://github.com/tensorflow/hub/archive/v{{ version }}.tar.gz
  sha256: d196f014719da297dc1893bd933d72d9af69e5f6c798882be0fbcc7a2f8d534a

build:
  number: 1
  # This is a noarch: python package, it contains no compiled code but a
  # compiler is required to convert protocol buffer definitions.
  # The build has only been tested on linux-64
  noarch: python
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=0.24
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.12.0
    - six >=1.10.0
    - protobuf >=3.4.0
    - tensorflow >=1.7.0

test:
  imports:
    - tensorflow_hub

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_file: LICENSE
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
    - jjhelmus
