{% set version = "0.5.0" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://pypi.io/packages/py2.py3/t/tensorflow_hub/tensorflow_hub-{{ version }}-py2.py3-none-any.whl
  sha256: 0c91f48a81cb0d1519bbff54d88f5f6cb4ae798569beea01080a42ede0ed7698

build:
  number: 0
  noarch: python
  # install using pip from the whl files on PyPI
  # b/c this uses bazel to build.
  script: python -m pip install --no-deps --ignore-installed tensorflow_hub-{{ version }}-py2.py3-none-any.whl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.12.0
    - six >=1.10.0
    - protobuf >=3.4.0
    - tensorflow >=1.7.0

test:
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow_hub  # [not linux]

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_file: tensorflow_hub-{{ version }}.dist-info/LICENSE.txt
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
