{% set version = "0.16.1" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://pypi.org/packages/py2.py3/t/tensorflow-hub/tensorflow_hub-{{ version }}-py2.py3-none-any.whl
  sha256: e10c184b3d08daeafada11ffea2dd46781725b6bef01fad1f74d6634ad05311f

build:
  number: 0
    # tf-keras is not available for osx-arm64 because of a failed import error.
    # see tf-keras feedstock
  skip: true  # [py<39 and py>=313 or (osx and x86_64)]
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation tensorflow_hub-{{ version }}-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - tf-keras >=2.14.1
    - tensorflow >=1.14.0

test:
  imports:
    - tensorflow_hub

about:
  home: https://www.tensorflow.org/hub/
  doc_url: https://www.tensorflow.org/hub/
  dev_url: https://github.com/tensorflow/hub
  license: Apache-2.0
  license_family: Apache
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
    - jjhelmus
