travis:
  secure:
    BINSTAR_TOKEN: o1hnx0LP0XJOdmHdC1QLbx/QIIURmx2fOuZCWRiApVcatERPOXrON58Y+QpNaOyYejFPwIrkommrn5YmqqzvR8o8fPSUTG2bbycx+JWRGWxL2wUPePn+JZ9fbYwkuIrIHdQ0P0n1npVgdYjAw0BT4xaCSOpTkdNeEH/tz6YY4r1OvAqVEQ4gopUm/7EmkWBN0MU523qzT5AlkGC2I7skqJUQpXr2Gnu5rP0EXzFAjAoKoJs98pnay9y6GO/GpG/537LZn53hvYSba+IvkDmImchnHZk1iVQVGiYZOA80AWQkEm8lTS0LKM+YsJDcn8ULrglV6Zw/ZcUOtd2bNRGymK4Jw64g+3Gwy5O5HqUfoJ72xdiYiKcn/k9/OQsyFCc6nJrXT/Y7UKniAXBYcaQM3AOUlUuA1KWXeSdbDRbCsH6PpJuKvGC9R42bC+afqHNfDxLegewcTK+uJu01PpyD0OUNBPBZRCAoPLeU0fEfu3KM7JHMSa+mRfHNEzFSZkC34JFclx4lJ7QiIYpgIR0tnz83qt3Gl3UCUuTzRDcBaCxafgN0lPYHREFSJcWWZSdvBvs2San7tVQZBRTXCbMnBISo0QIATgQcrcJ3LPoIQvzyrAnhIDUpoMYHAxgVNgCfSbABA+QmcbBXwKsXrgriuprcZ60vvKWnIR9PrXCWLiY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
