travis:
  secure:
    BINSTAR_TOKEN: F0mElYK75YJXgHRw5P+0Dfp6uaTbVpu8HzttHP3+WibJk7wEtEXjfMmhk55rRO6ktrGTvt3tlWCqi1bqSArsWTbHhUO9RVg30kNaOHmKuGdhWLbUNMxcNbCU6MahxCpSi/dDM0nSx35cvbcWzcAw1QeCKpRo8gFGt38LkFGXgNapsszEB7tdln3Nj1v8MYAlJJ/S4tiXW47R0+rg/y3ccKdSGIl1sb3dT+7dC8oJEvXyboAnGsZYUJ4b2L8GB2gIokrma4SVjJJPWFf1N3xEVyVd8afWMMEnWF+Rpqbd+FI7p4t3UzWzEWgwgXMk55Lo2Lu44CQiSUN3w/Me4lBA6XokBSNl3QEpRtsHg81whgAXR91nBTVb4e67bGH83u1f7y82dD+G3wfzXzIQYdhqbquNZ8ptMIWe+w6snBkkpIQT+z2Be3fR/ape4C99/RG9jf5khkEmkSGH7e7XOzKlIDH2auClFGM2t7r3lCDdyYpUlPAkgrMq3TLvQp+MKtom3aRK08QxFbfC9WbTfxc4S7y96m2XLoPjVR5lUo6QEb2OWKEjXgfrZaPTBijUiSu3qDnaJzQkXNqRigH76sswJB1OOeXIrrmhqluLyCDyyMvBRv4RvBDj6k1xoLnZ6RGD1+5hn6/2ZVR0LTxUwXk766MkGtIzT65li2i5RQgtnwA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
